# My workflow

name: my first workflow

# Trigger: Webhook event
on: [push, pull_request]

jobs:
  # job
  job_1:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - name: my first step
        uses: actions/checkout@v2
        
      - name: my second step
        run: echo "Hello world"
        shell: bash

      - name: my third step
        run: |
          echo "fist hello"
          echo "second hello"
        shell: bash

      - name: The job has succeeded
        if: ${{ sucess() }}
        run: echo "successfully completed"
